Moving logic assets to main game
Project-Rekt/rekt pull request #1
Opened 2020-02-05 18:33 UTC by KingJeremyNg

2020-02-05 18:34 UTC, KingJeremyNg commented
Initial pull request to get logic team started

2020-02-05 18:42 UTC, Squishy123 requested changes

2020-02-05 18:42 UTC, Squishy123 commented on src/routes.js
> +import TowerDefense from './routes/td/td.svelte'
Change folder names
```suggestion
import TowerDefense from './routes/towerdefense/towerdefense.svelte'
```

2020-02-05 18:42 UTC, Squishy123 commented on src/routes/td/classes/player.js
> +export default class Player {
These are probably gonna be actors?

2020-02-05 18:42 UTC, Squishy123 commented on src/routes/td/td.svelte
> +<!--<script>
Set this up. Look at pacman demo

2020-02-17 00:32 UTC, Squishy123 approved these changes
Looks good to me!

2020-03-10 19:36 UTC, merged